### ISSUE TITLE
Bash command not found when entered in gitpod

### ISSUE THREAD

**Issue by JonR2002** [TheEvergreenStateCollege/upper-division-cs#10]
gitpod /workspace/upper-division-cs (Elson-array-links) $ bash
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $ bash
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $ bash
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $ ls
Collaboration.md  docs  dsa-23au  LICENSE  notes  README.md  scripts
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $ bash
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $ echo $SHELL
/bin/bash
bash: __vsc_prompt_cmd_original: command not found
gitpod /workspace/upper-division-cs (Elson-array-links) $

**Comment by halcyonseeker** [comment]
It looks like one of bash's startup files is trying to call the `__vsc_prompt_cmd_original` which is not present; bash should still work fine.

Since you ran `bash` multiple times, you're now running in 4 nested bash shells, if you encounter problems running `exit` 4 or 5 times then running `bash` might fix it.

**Comment by pswish** [comment]
i used `unset PROMPT_COMMAND` to mute that error

**Comment by learner-long-life** [comment]
@JonR2002 still having this problem?

**Comment by learner-long-life** [comment]
Feel free to re-open this issue if you're still experiencing it.
