### ISSUE TITLE
Gitpod use exceeded, what next...

### ISSUE THREAD

**Issue by pswish** [TheEvergreenStateCollege/upper-division-cs#134]
I exceeded my gitpod allowance today. As a laptop backup seemed legit, I was warned by `brew` that my OS was too old to install python 3.x and then Maven complained the same way. What now? I set up my IDE (VS Code) to connect to an EC2 instance which is much cheaper than buying a new computer. There probably is a workaround that takes n hours. 

Summary: If you find yourself in a similar situation and want to set up an EC2 desktop to work on coding, let me know if you need help.

**Comment by learner-long-life** [comment]
Thanks for addressing this @pswish I didn't realize python3.x and maven would be sensitive to recent OS X versions.

You can run Docker Desktop on your laptop / local machine, and then build the gitpod image (which is just a docker image) from
https://github.com/TheEvergreenStateCollege/upper-division-cs/blob/main/.gitpod.Dockerfile

Alternatively, using an EC2 instance is a useful skill going forward, and also for next quarter when we talk about web engineering.

https://code.visualstudio.com/docs/remote/ssh-tutorial

In my experience, the `t2.micro` instances are too puny for most development tasks and the vscode-server component. The `t2.medium` can handle it, but there is no free trial for it. Let's brainstorm in class on Thursday about possible solutions.

**Comment by pswish** [comment]
Likewise, I was like OS11 is too old?!? `t2.micro` is what I picked for now and then installed maven much quicker but when I was a developer@Amazon , we always used `someting.xlarge`.

**Comment by learner-long-life** [comment]
It looks like IntelliJ should come with Maven bundled with it, so there's no need for a separate install. Can you double-check @pswish ?

https://www.jetbrains.com/help/idea/maven-support.html

https://www.jetbrains.com/help/idea/convert-a-regular-project-into-a-maven-project.html#add_maven_support

However, I do think to use built-in Maven, you need to use the menu items for building and running, and not the terminal commands like `mvn test`. That's good for us to include in SoftwareSetup.md in the future.

<img width="359" alt="image" src="https://github.com/TheEvergreenStateCollege/upper-division-cs/assets/148553/9360e9fa-95d3-4c55-83a2-c0a1f6b83afd">

<img width="1062" alt="image" src="https://github.com/TheEvergreenStateCollege/upper-division-cs/assets/148553/2e92929d-bfb0-4358-a7a2-c4aa4c50c139">

**Comment by learner-long-life** [comment]
It looks like GitHub workspace is a good alternative to GitPod for many tasks, but the AWS server experience lets you run larger computational loads, keep larger datasets on disk, and keep the data private. I'll tag this "help-wanted" to let folks work on it for their Assignment 7, Problem 2.

**Comment by learner-long-life** [comment]
Closing for now, I think folks have more workarounds for GitPod usage being exceeded.

@pswish @EvergreenTor you might like MacPorts.

https://www.macports.org/install.php

I use it alongside and sometimes instead of Homebrew, and it does not deprecate older versions of OSX as far as I can tell.

You can run

```
sudo port install telnet
```

for example
