### ISSUE TITLE
Gitpod use exceeded, what next...

### ISSUE THREAD

**Issue by pswish** [TheEvergreenStateCollege/upper-division-cs#135]
I exceeded my gitpod allowance today. As a laptop backup seemed legit, i was warned by brew that my OS was too old to install python 3.x and thee Maven complained the same way. What now? I set up my IDE to connect to an EC2 instance which is much cheaper than a new computer. 

Summary: If you find yourself in a similar situation and want to set up an EC2 desktop to work on coding, let me know if you help.

**Comment by learner-long-life** [comment]
Duplicates #134 , check there to work on this issue.
