### ISSUE TITLE
Add maven to GitPod image

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#19]
To build projects.

By sourcing the file `scripts/.shrc` (and making sure we also run bash by default for each user who instantiates this image), we get the GraalVM JDK on the path.

`/opt/graalvm.../bin`

**Comment by WinstonShine** [comment]
Made a pull request to add maven to the image and add both maven and java to path during build.
https://github.com/TheEvergreenStateCollege/upper-division-cs/pull/21
It seems to work fine but i also have never used maven before.

**Comment by pswish** [comment]
Here is the error i see when running `man` -e:

`org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: pre-clean, clean, post-clean, validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy.`

**Comment by pswish** [comment]
Adding a ':' at the end of line 28 in app.java, adding my gitpod generated id.rsa_pub, and navigating to the array-links directory, I ran `mvn package` and `mvn test` with a successful build.

`gitpod /workspace/upper-division-cs/dsa-23au/java-dsa/arrays-links (main) $ pwd
/workspace/upper-division-cs/dsa-23au/java-dsa/arrays-links`

`[INFO] Building jar: /workspace/upper-division-cs/dsa-23au/java-dsa/arrays-links/target/arrays-links-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.690 s
[INFO] Finished at: 2023-09-30T04:11:02Z
[INFO] ------------------------------------------------------------------------
gitpod /workspace/upper-division-cs/dsa-23au/java-dsa/arrays-links (main) $ mvn test
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< dev.codewithfriends:arrays-links >------------------
[INFO] Building arrays-links 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.0.2:resources (default-resources) @ arrays-links ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- compiler:3.8.0:compile (default-compile) @ arrays-links ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- resources:3.0.2:testResources (default-testResources) @ arrays-links ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /workspace/upper-division-cs/dsa-23au/java-dsa/arrays-links/src/test/resources
[INFO] 
[INFO] --- compiler:3.8.0:testCompile (default-testCompile) @ arrays-links ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- surefire:2.22.1:test (default-test) @ arrays-links ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.codewithfriends.ArrayWrapperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in dev.codewithfriends.ArrayWrapperTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.605 s
[INFO] Finished at: 2023-09-30T04:11:11Z
[INFO] ------------------------------------------------------------------------

**Comment by learner-long-life** [comment]
Thanks @pswish adding your SSH public key shouldn't be necessary, but we can track it in another issue. If it keeps being necessary.

Lots of people, including me, have started a fresh GitPod workspace with working `mvn` today.
🚀 🌞  @WinstonShine
