### ISSUE TITLE
maven plugin warnings

### ISSUE THREAD

**Issue by JonR2002** [TheEvergreenStateCollege/upper-division-cs#211]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for dev.codewithfriends:sorting:jar:1.0-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jar-plugin @ line 63, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by learner-long-life** [comment]
I think this has been fixed, I haven't been able to reproduce. Feel free to re-open if you notice it happening again.
