### ISSUE TITLE
Add Python and Haskell support to GitPod image

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#321]
Several students have found it easier to use Python for processing data, or have expressed a preference for building on previous Haskell experience.

This task is to install software into the GitPod dockerfile that will allow students to run and reproduce each others Python results, if used in their final project, and also to demonstrate knowledge of Data Structures & Algorithms in Haskell.

GraalVM contains a Python-compatible runtime installed with

```
gu install python
```

similar to its NodeJS runtime that is already in the Dockerfile.

I know less about the Haskell ecosystem, I believe the Glasgow Haskell Compiler (GHC) and Stack ecosystem are popular. I'll rely on your knowledge and help on this @WinstonShine . Do you think this task is feasiable?

**Comment by whereismyprozac** [comment]
This is a good article on how to process and or cleanse data using python.
https://medium.com/@panData/mastering-data-cleaning-in-python-faaa0a668852#:~:text=Python%20offers%20several%20powerful%20libraries%20for%20data%20cleaning%2C,library%20with%20tools%20for%20preprocessing%20and%20imputing%20data

**Comment by whereismyprozac** [comment]
sklearn.impute is a good one for replacing abnormal values.

**Comment by learner-long-life** [comment]
> sklearn.impute is a good one for replacing abnormal values.

Thanks @whereismyprozac this is a good tip. I think a good place to gather learnings like this is in a README.md file here in [your project directory](https://github.com/TheEvergreenStateCollege/upper-division-cs/tree/main/dsa-23au/python-dsa/Stella_pyhw), and then I'll mention it to @EvergreenTor and @WestDav who have a very similar need. They use biometric data with a lot of noise from an Apple watch.

**Comment by learner-long-life** [comment]
Closing this issue as @WinstonShine mentioned adding the Haskell compiler (GHC) doubles the image size, which doesn't seem reasonable to ask non-Haskell users to experience when starting up their own workspaces. It's a useful datapoint, and we'll save it judiciously for a future, class-specific docker image only for Haskell.
