### ISSUE TITLE
Implement LinkedListWrapper.contains

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#37]
![image](https://github.com/TheEvergreenStateCollege/upper-division-cs/assets/148553/8dd52041-843f-4dd4-9c61-27c3b11c25d7)

**Comment by learner-long-life** [comment]
@faulkdf @DawsonWhi it looks like you are currently working on this in the `faulkdf-dawsonwhi` branch
https://github.com/TheEvergreenStateCollege/upper-division-cs/tree/faulkdf-dawsonwhi

**Comment by learner-long-life** [comment]
Please commit and push and create a pull request when you get a chance.

**Comment by DawsonWhi** [comment]
we resolved a previous conflict on the `faulkdf-dawsonwhi` branch and got rid of that branch, and made a new branch `dawsonwhi-faulkdf` to work on this problem. working on making a pull request now
