### ISSUE TITLE
Implement LinkedListWrapperTest.add test case

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#38]
![image](https://github.com/TheEvergreenStateCollege/upper-division-cs/assets/148553/df3c04d8-3373-46b9-b062-f92cedccd0e7)

 // create an array of 4 grocery items as Strings
        // create a LinkedList
        // add them one by one
        // use assertEquals to check they're added in correct order
        // insert a 5th grocery item (as a string)
        // check the order again

**Comment by AnnieNg89** [comment]
@learner-long-life would you please assign me in this asignment?

**Comment by learner-long-life** [comment]
I've combined the `testAdd` methods for both `ArrayWrapper` and `LinkedListWrapper` in this other PR #109 .
We'll close this.
