### ISSUE TITLE
Add support for Rust, NodeJS, tcpdump, telnet, netcat to GitPod image

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#625]
We would like to use the Rust and NodeJS toolchains in Web Engineering this quarter with our GitPod image, as a convenience in class for students who wish to work on school computers, and also to easily demo projects in Week 5 and Week 10.

These lines make some progress in this direction in #624 , but error out because the `rustup` installation requires interactive prompts.
There might be a `-y` flag that selects the default option, which is good enough for us (the long-term support version is preferred, but the latest nightly build is okay for now).

So I remove those lines for now. Any help is appreciated. @WinstonShine @aquinnallen 

## Testing

To make sure all necessary Rust and Node tools are installed, we wish the run the following tools successfully in the image, without errors.

### Rust

```

```

## Networking Tools

We also need the following tools for the networking portion:
* `tcpdump` for network traffic analysis
* `telnet` and `netcat` for testing basic connectivity and simulating web protocols

**Comment by aquinnallen** [comment]
This now works, but you have to sudo su to see that rust is there, probably because the script was running as root when it installed not gitpod.. probably can su gitpod before install, then sudo su root after to fix this.. I will try it

**Comment by aquinnallen** [comment]
Okay tried that, the user gitpod doesnt exist yet when the Dockerfile is being executed.

To use the rust toolchain we will need to change to root user.

Not sure if I can find a way around this, but overall all requested tools are now installed in the workspace. Folks will need to delete the old workspace and then build a new one to get my changes.

**Comment by WinstonShine** [comment]
> Okay tried that, the user gitpod doesnt exist yet when the Dockerfile is being executed.
> 
> To use the rust toolchain we will need to change to root user.
> 
> Not sure if I can find a way around this, but overall all requested tools are now installed in the workspace. Folks will need to delete the old workspace and then build a new one to get my changes.

The gitpod user could possibly be added during the build and switched to before installing rust
```
# Create the gitpod user. UID must be 33333.
RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod
```

referenced from https://www.gitpod.io/docs/configure/workspaces/workspace-image

**Comment by aquinnallen** [comment]
@WinstonShine do you want to give that a try then? I thought that might work but I didn't check the gitpod docks to be sure nor try it. Having to switch to root doesn't bother me but I see the value in making it consistent.

**Comment by WinstonShine** [comment]
> @WinstonShine do you want to give that a try then? I thought that might work but I didn't check the gitpod docks to be sure nor try it. Having to switch to root doesn't bother me but I see the value in making it consistent.

yes I can try and see if it works later today
