### ISSUE TITLE
gitignore config file

### ISSUE THREAD

**Issue by ddnsc** [TheEvergreenStateCollege/upper-division-cs#7]
add config file to gitignore to keep original repository from being changed... unless you like chaos.

**Comment by learner-long-life** [comment]
I agree, if this means the `git-config.sh` file.

**Comment by ddnsc** [comment]
> I agree, if this means the `git-config.sh` file.

That's what I mean.

**Comment by ddnsc** [comment]
git-config.sh added to .gitignore
