### ISSUE TITLE
Error in .gitpod.yml - gitpod.gitpod-web extension is not found in Open VSX

### ISSUE THREAD

**Issue by de02E** [TheEvergreenStateCollege/upper-division-cs#9]
There's an error in the .gitpod.yml file, saying that the gitpod.gitpod-web extension can't be found, despite me being able to find it. Is this because it is enabled globally?

**Comment by learner-long-life** [comment]
<img width="1254" alt="image" src="https://github.com/TheEvergreenStateCollege/upper-division-cs/assets/148553/5cca8f9d-9d62-4bd2-9233-20b9828038dc">

I'm not sure. It doesn't appear to stop us from developing as we need to, so I'm going to close as "won't fix" for now. It could just be a linting issue.

**Comment by learner-long-life** [comment]
Feel free to re-open if we later discover it is blocking us.
